const projectListings = [
  {
    project_title: "Smart Resume Analyzer & Job Matcher",
    project_description:
      "An AI-powered platform that scans resumes, extracts key skills, and matches candidates to relevant job openings. It uses NLP and ML to analyze candidate profiles and job descriptions.",
    company_name: "Microsoft",
    skills_required: [
      "MERN Stack",
      "Natural Language Processing",
      "Machine Learning",
      "REST APIs",
    ],
    basic_requirements: [
      "Good understanding of Node.js",
      "Experience with MongoDB",
      "Knowledge of AI libraries",
    ],
    salary: 18000,
    applicants: 145,
    selected_applicants: 12,
    project_status: "Active",
    time_duration: "3 months",
    number_of_applicants_starts_on: "2025-10-26",
    project_milestones: [
      "Requirement Gathering & Architecture Design",
      "Resume Parsing Module Development",
      "Job Matching Algorithm Integration",
      "Frontend Dashboard Implementation",
      "Testing & Deployment",
    ],
    projectApproval: "Approved",
    mentor: {
      mentor_name: "Dr. Priya Mehta",
      email: "priya.mehta@microsoft.com",
      number: "+91 9876543210",
      designation: "Lead Data Scientist",
      mentor_image: "https://example.com/images/priya_mehta.jpg",
    },
  },
  {
    project_title: "AI Interview Prep Coach",
    project_description:
      "A web-based platform that simulates interview sessions using AI. It provides instant feedback on answers, evaluates communication, and suggests improvements.",
    company_name: "Google",
    skills_required: ["React", "Express.js", "Speech Recognition", "TensorFlow"],
    basic_requirements: [
      "Strong grasp of frontend development",
      "Knowledge of AI/ML basics",
      "Good problem-solving skills",
    ],
    salary: 20000,
    applicants: 132,
    selected_applicants: 10,
    project_status: "Upcoming",
    time_duration: "4 months",
    number_of_applicants_starts_on: "2025-10-27",
    projectApproval: "Approved",
    project_milestones: [
      "UI/UX Design and Wireframing",
      "Speech-to-Text API Integration",
      "AI Model Training for Interview Q&A",
      "Feedback Engine Development",
      "Final Testing & Cloud Deployment",
    ],
    mentor: {
      mentor_name: "Mr. Rajesh Iyer",
      email: "rajesh.iyer@google.com",
      number: "+91 9988776655",
      designation: "Senior AI Engineer",
      mentor_image: "https://example.com/images/rajesh_iyer.jpg",
    },
  },
  {
    project_title: "RentSphere - Peer-to-Peer Rental Platform",
    project_description:
      "A platform where people can rent out their personal items such as electronics, tools, and appliances to others, promoting a sustainable and cost-efficient rental ecosystem.",
    company_name: "Capgemini",
    skills_required: [
      "Next.js",
      "MongoDB",
      "AWS",
      "Payment Gateway Integration",
    ],
    basic_requirements: [
      "Experience with cloud hosting",
      "Secure authentication knowledge",
      "Basic UI design skills",
    ],
    salary: 19000,
    applicants: 120,
    selected_applicants: 9,
    project_status: "Upcoming",
    time_duration: "6 months",
    number_of_applicants_starts_on: "2025-10-28",
    projectApproval: "Pending",
    project_milestones: [
      "Platform Design & Database Setup",
      "User Authentication & Profile Management",
      "Rental Listing & Search Feature",
      "Payment Gateway & Booking System",
      "Security Testing & Launch",
    ],
    mentor: {
      mentor_name: "Ms. Neha Kapoor",
      email: "neha.kapoor@capgemini.com",
      number: "+91 9123456789",
      designation: "Full Stack Developer",
      mentor_image: "https://example.com/images/neha_kapoor.jpg",
    },
  },
  {
    project_title: "MediConnect - Smart Healthcare Portal",
    project_description:
      "A healthcare management system that connects doctors, patients, and pharmacies. It enables online consultations, e-prescriptions, and medicine delivery tracking.",
    company_name: "Google",
    skills_required: ["Django", "React", "PostgreSQL", "RESTful APIs"],
    basic_requirements: [
      "Knowledge of backend frameworks",
      "Database design understanding",
      "Experience with frontend libraries",
    ],
    salary: 22000,
    applicants: 180,
    selected_applicants: 14,
    project_status: "Upcoming",
    time_duration: "5 months",
    number_of_applicants_starts_on: "2025-11-01",
    projectApproval: "Pending",
    project_milestones: [
      "Requirement Analysis",
      "Doctor-Patient Module Creation",
      "E-Prescription Integration",
      "Pharmacy API Linking",
      "Deployment & Maintenance",
    ],
    mentor: {
      mentor_name: "Dr. Sanjay Kulkarni",
      email: "sanjay.kulkarni@google.com",
      number: "+91 9812345678",
      designation: "Chief Software Architect",
      mentor_image: "https://example.com/images/sanjay_kulkarni.jpg",
    },
  },
  {
    project_title: "EduVerse - Virtual Classroom Platform",
    project_description:
      "A cloud-based platform that allows educators to host virtual classrooms with real-time quizzes, whiteboards, and attendance tracking.",
    company_name: "Tata Consultancy Services",
    skills_required: ["Node.js", "Socket.io", "React", "Firebase"],
    basic_requirements: [
      "Understanding of real-time communication",
      "Experience with Firebase",
      "Strong frontend development skills",
    ],
    salary: 17500,
    applicants: 102,
    selected_applicants: 8,
    project_status: "Upcoming",
    time_duration: "4 months",
    number_of_applicants_starts_on: "2025-11-10",
    projectApproval: "Pending",
    project_milestones: [
      "Platform Planning & UI Design",
      "Real-time Class Integration",
      "Interactive Tools Implementation",
      "Data Storage Setup",
      "Testing and Live Launch",
    ],
    mentor: {
      mentor_name: "Mrs. Kavita Sharma",
      email: "kavita.sharma@tcs.com",
      number: "+91 9001122334",
      designation: "Education Technology Specialist",
      mentor_image: "https://example.com/images/kavita_sharma.jpg",
    },
  },
  {
    project_title: "EcoRoute - Smart Transportation Optimizer",
    project_description:
      "An AI-based solution that suggests eco-friendly and time-efficient routes for logistics and delivery systems to reduce carbon footprint.",
    company_name: "Google",
    skills_required: ["Python", "Flask", "Google Maps API", "Machine Learning"],
    basic_requirements: [
      "Knowledge of APIs and routing systems",
      "Basic ML model implementation",
      "Good Python skills",
    ],
    salary: 21000,
    applicants: 165,
    selected_applicants: 12,
    project_status: "Upcoming",
    time_duration: "5 months",
    number_of_applicants_starts_on: "2025-11-20",
    projectApproval: "Pending",
    project_milestones: [
      "Requirement Gathering & Route Analysis",
      "Map API Integration",
      "AI Route Optimization Engine",
      "Dashboard Development",
      "Testing & Deployment",
    ],
    mentor: {
      mentor_name: "Mr. Arjun Deshmukh",
      email: "arjun.deshmukh@translogic.ai",
      number: "+91 9822334455",
      designation: "Transportation Data Scientist",
      mentor_image: "https://example.com/images/arjun_deshmukh.jpg",
    },
  },
  {
    project_title: "FinTrackr - Personal Finance Dashboard",
    project_description:
      "A secure web app that helps users manage expenses, track investments, and visualize monthly budgets through charts and insights.",
    company_name: "Meta",
    skills_required: ["Vue.js", "Node.js", "Chart.js", "MongoDB"],
    basic_requirements: [
      "Experience with REST APIs",
      "Understanding of financial data handling",
      "Basic frontend chart integration",
    ],
    salary: 16000,
    applicants: 110,
    selected_applicants: 7,
    project_status: "Upcoming",
    time_duration: "3 months",
    number_of_applicants_starts_on: "2025-12-01",
    projectApproval: "Pending",
    project_milestones: [
      "Dashboard UI/UX Design",
      "Expense Tracker Module",
      "Investment Tracker Integration",
      "Data Visualization Setup",
      "Security Review & Deployment",
    ],
    mentor: {
      mentor_name: "Ms. Riya Patel",
      email: "riya.patel@meta.com",
      number: "+91 9033445566",
      designation: "Financial Software Engineer",
      mentor_image: "https://example.com/images/riya_patel.jpg",
    },
  },
  {
    project_title: "AgriSense - Smart Farming Assistant",
    project_description:
      "An IoT-powered system that collects soil, temperature, and humidity data to provide crop suggestions and irrigation alerts.",
    company_name: "Google",
    skills_required: ["IoT", "Python", "Flask", "Data Analytics"],
    basic_requirements: [
      "Knowledge of sensor data processing",
      "Basic hardware integration understanding",
      "Data visualization knowledge",
    ],
    salary: 23000,
    applicants: 195,
    selected_applicants: 13,
    project_status: "Upcoming",
    time_duration: "6 months",
    number_of_applicants_starts_on: "2025-12-10",
    projectApproval: "Pending",
    project_milestones: [
      "IoT Hardware Setup",
      "Sensor Data API Creation",
      "Crop Recommendation Engine",
      "Dashboard Development",
      "Pilot Testing & Launch",
    ],
    mentor: {
      mentor_name: "Dr. Sneha Reddy",
      email: "sneha.reddy@agritechglobal.com",
      number: "+91 9911223344",
      designation: "Agritech Research Engineer",
      mentor_image: "https://example.com/images/sneha_reddy.jpg",
    },
  },
  {
    project_title: "ShopEase - Smart E-commerce Recommendation System",
    project_description:
      "An AI-driven e-commerce platform that personalizes product recommendations based on user behavior and preferences.",
    company_name: "Google",
    skills_required: ["React", "Node.js", "TensorFlow", "MongoDB"],
    basic_requirements: [
      "Experience with recommendation systems",
      "Knowledge of backend integration",
      "Strong data handling skills",
    ],
    salary: 21000,
    applicants: 140,
    selected_applicants: 9,
    project_status: "Upcoming",
    time_duration: "5 months",
    number_of_applicants_starts_on: "2025-12-20",
    projectApproval: "Pending",
    project_milestones: [
      "User Data Analysis",
      "Recommendation Engine Design",
      "Frontend Personalization",
      "A/B Testing & Feedback Loop",
      "Final Deployment",
    ],
    mentor: {
      mentor_name: "Mr. Manish Bhatt",
      email: "manish.bhatt@retailnext.ai",
      number: "+91 9700112233",
      designation: "AI Systems Architect",
      mentor_image: "https://example.com/images/manish_bhatt.jpg",
    },
  },
  {
    project_title: "CityPulse - Smart City Dashboard",
    project_description:
      "A centralized data dashboard for monitoring city utilities like traffic, air quality, and waste management in real-time.",
    company_name: "Tata Consultancy Services",
    skills_required: ["Angular", "Firebase", "Data Visualization", "IoT"],
    basic_requirements: [
      "Understanding of public data APIs",
      "Experience with dashboards",
      "Firebase Realtime Database skills",
    ],
    salary: 24000,
    applicants: 170,
    selected_applicants: 11,
    project_status: "Upcoming",
    time_duration: "6 months",
    number_of_applicants_starts_on: "2026-01-01",
    projectApproval: "Pending",
    project_milestones: [
      "API Integration Setup",
      "Traffic & Environment Modules",
      "Visualization Dashboard",
      "User Roles & Access Control",
      "Deployment and Maintenance",
    ],
    mentor: {
      mentor_name: "Dr. Nikhil Bansal",
      email: "nikhil.bansal@tcs.com",
      number: "+91 9877766554",
      designation: "IoT Systems Expert",
      mentor_image: "https://example.com/images/nikhil_bansal.jpg",
    },
  },
  {
    project_title: "FitBuddy - AI Fitness Coach",
    project_description:
      "A mobile-friendly AI app that generates personalized fitness plans and tracks user activity using wearable integration.",
    company_name: "Google",
    skills_required: ["React Native", "Python", "TensorFlow Lite", "Firebase"],
    basic_requirements: [
      "Experience in mobile app development",
      "Basic ML model understanding",
      "Knowledge of Firebase Auth & Storage",
    ],
    salary: 19000,
    applicants: 150,
    selected_applicants: 10,
    project_status: "Upcoming",
    time_duration: "4 months",
    number_of_applicants_starts_on: "2026-01-10",
    projectApproval: "Pending",
    project_milestones: [
      "UI Design & API Setup",
      "Workout Plan Generator",
      "Wearable Data Integration",
      "Feedback & Analytics Engine",
      "Beta Testing & Release",
    ],
    mentor: {
      mentor_name: "Ms. Tanya Rao",
      email: "tanya.rao@google.com",
      number: "+91 9955446677",
      designation: "Health Data Analyst",
      mentor_image: "https://example.com/images/tanya_rao.jpg",
    },
  },
  {
    project_title: "FoodScan - Nutrition Detector App",
    project_description:
      "An AI app that scans food items through the camera and provides nutritional breakdown and health suggestions.",
    company_name: "Google",
    skills_required: ["Flutter", "Firebase", "TensorFlow", "REST APIs"],
    basic_requirements: [
      "Knowledge of image recognition",
      "Mobile development experience",
      "Basic nutrition domain knowledge",
    ],
    salary: 17000,
    applicants: 100,
    selected_applicants: 8,
    project_status: "Upcoming",
    time_duration: "3 months",
    number_of_applicants_starts_on: "2026-01-15",
    projectApproval: "Pending",
    project_milestones: [
      "Model Training for Food Recognition",
      "Image API Integration",
      "UI Design and Testing",
      "Health Recommendation Setup",
      "Final App Launch",
    ],
    mentor: {
      mentor_name: "Dr. Ananya Bose",
      email: "ananya.bose@google.com",
      number: "+91 9788996655",
      designation: "Computer Vision Specialist",
      mentor_image: "https://example.com/images/ananya_bose.jpg",
    },
  },
  {
    project_title: "CyberShield - Threat Detection System",
    project_description:
      "A cybersecurity system that detects network anomalies and potential threats in real-time using ML models.",
    company_name: "Google",
    skills_required: ["Python", "Kubernetes", "Cybersecurity", "ML"],
    basic_requirements: [
      "Understanding of network protocols",
      "Knowledge of anomaly detection algorithms",
      "Experience with containerized deployments",
    ],
    salary: 25000,
    applicants: 210,
    selected_applicants: 15,
    project_status: "Upcoming",
    time_duration: "6 months",
    number_of_applicants_starts_on: "2026-02-01",
    projectApproval: "Pending",
    project_milestones: [
      "Threat Dataset Preparation",
      "Model Training & Testing",
      "Network Monitoring Dashboard",
      "Containerization & Deployment",
      "Security Audits & Documentation",
    ],
    mentor: {
      mentor_name: "Mr. Aditya Menon",
      email: "aditya.menon@google.com",
      number: "+91 9123456677",
      designation: "Cybersecurity Engineer",
      mentor_image: "https://example.com/images/aditya_menon.jpg",
    },
  },
  {
    project_title: "VisionAid - Accessibility Assistant",
    project_description:
      "An AI-powered tool that narrates on-screen content and objects for visually impaired users.",
    company_name: "Microsoft",
    skills_required: ["JavaScript", "TensorFlow", "Speech Synthesis API"],
    basic_requirements: [
      "Basic AI model implementation",
      "Frontend scripting experience",
      "Understanding accessibility standards",
    ],
    salary: 18000,
    applicants: 115,
    selected_applicants: 9,
    project_status: "Upcoming",
    time_duration: "4 months",
    number_of_applicants_starts_on: "2026-02-10",
    projectApproval: "Pending",
    project_milestones: [
      "Accessibility Framework Design",
      "Text & Object Recognition Integration",
      "Voice Narration Setup",
      "User Testing & Optimization",
      "Launch and Feedback Collection",
    ],
    mentor: {
      mentor_name: "Ms. Meera Jain",
      email: "meera.jain@microsoft.com",
      number: "+91 9777665544",
      designation: "AI Accessibility Engineer",
      mentor_image: "https://example.com/images/meera_jain.jpg",
    },
  },
  {
    project_title: "TravelMate - Personalized Trip Planner",
    project_description:
      "An intelligent travel planner that suggests itineraries, accommodations, and activities based on user preferences.",
    company_name: "Amazon",
    skills_required: ["React", "Node.js", "Google Places API", "MongoDB"],
    basic_requirements: [
      "API handling skills",
      "Experience in web app design",
      "Basic data visualization understanding",
    ],
    salary: 20000,
    applicants: 140,
    selected_applicants: 10,
    project_status: "Upcoming",
    time_duration: "5 months",
    number_of_applicants_starts_on: "2026-02-20",
    projectApproval: "Pending",
    project_milestones: [
      "User Profile Setup",
      "Destination & Hotel API Integration",
      "Dynamic Itinerary Engine",
      "Review & Rating Module",
      "Final Deployment",
    ],
    mentor: {
      mentor_name: "Mr. Rohit Sinha",
      email: "rohit.sinha@amazon.com",
      number: "+91 9900112234",
      designation: "Senior Software Engineer",
      mentor_image: "https://example.com/images/rohit_sinha.jpg",
    },
  },
  {
    project_title: "StreamSync - Cloud Video Collaboration Tool",
    project_description:
      "A video collaboration platform for remote teams to stream, annotate, and discuss video content in real-time.",
    company_name: "Amazon",
    skills_required: ["React", "WebRTC", "Node.js", "AWS S3"],
    basic_requirements: [
      "Knowledge of real-time communication",
      "Experience with cloud file handling",
      "Good frontend performance optimization skills",
    ],
    salary: 22000,
    applicants: 160,
    selected_applicants: 12,
    project_status: "Upcoming",
    time_duration: "6 months",
    number_of_applicants_starts_on: "2026-03-01",
    projectApproval: "Approved",
    project_milestones: [
      "Requirement Analysis & Wireframe",
      "WebRTC Integration",
      "Annotation Tools Setup",
      "Cloud Storage Configuration",
      "Beta Testing & Deployment",
    ],
    mentor: {
      mentor_name: "Dr. Varun Joshi",
      email: "varun.joshi@amazon.com",
      number: "+91 9334455566",
      designation: "Video Systems Architect",
      mentor_image: "https://example.com/images/varun_joshi.jpg",
    },
  },
];

module.exports = { data: projectListings };




